services:
    canal_tp.navitia:
      class: Navitia\Component\Service\ServiceFacade
      factory: [Navitia\Component\Service\ServiceFacade, getInstance]
      arguments: ['@navitia_profiler']
      calls:
          - [ setConfiguration, ['%canaltp.navitia.config%']]
